CREATE DATABASE [Disco]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Disco', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Disco.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Disco_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Disco_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Disco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Disco] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Disco] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Disco] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Disco] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Disco] SET ARITHABORT OFF 
GO

ALTER DATABASE [Disco] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Disco] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Disco] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Disco] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Disco] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Disco] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Disco] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Disco] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Disco] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Disco] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Disco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Disco] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Disco] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Disco] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Disco] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Disco] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Disco] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Disco] SET RECOVERY FULL 
GO

ALTER DATABASE [Disco] SET  MULTI_USER 
GO

ALTER DATABASE [Disco] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Disco] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Disco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Disco] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Disco] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Disco] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Disco] SET  READ_WRITE 
GO



